name: Table Sum QA Check
on: [push, workflow_dispatch]

jobs:
  scrape-tables:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code (with email 24108017588fs.study.iitm.ac.in)
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Install Playwright
        run: |
          npm init -y
          npm install playwright
      
      - name: Run scraping script
        run: node scrape-tables.js
      
      - name: Upload results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: scrape-results
          path: |
            scrape-tables.js
